//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCRUDmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int Admi_id { get; set; }
        public Nullable<int> Stu_id { get; set; }
        public Nullable<int> Sub_id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
